# HW

In [2]:
import numpy as np
import pandas as pd

##### Загрузите датасет titanic.csv

In [3]:
df_titanic = pd.read_csv('titanic.csv')

In [4]:
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df_titanic.shape

(891, 12)

In [6]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


> Обратите внимание на разное количество значений переменных
Если это так - то у вас пропуски в данных. Такое бывает. 
Например в этом датасете не получилось выяснить всех подробностей у некоторых людей в виду утери данных, невозможности узнать или восстановить их

In [7]:
df_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

> Давайте возьмем для начала только несколько признаков, позже - вы увеличите их количество и сделаете соответствующую обработку.

In [12]:
meanf=df_titanic.dropna()['Fare'].mean()


In [13]:
columns = ['Sex', 'Age', 'Pclass', 'Survived']

In [14]:
simple_train = df_titanic[columns].loc[:160]
simple_test = df_titanic[columns].loc[160:]
simple_train.shape

(161, 4)

> мы пока не умеем на уровне алгоритма работать с пропущенными значениями. 
Представьте вам дают 5-мерный вектор у которого заполнены только три компоненты и другой такой же вектор но у него заполнены лишь две  компоненты.  Как померить их сходство????

distance_between( [1,0,1, NaN, NaN], [NaN, 1, 1, NaN, NaN] )


> один из вариантов - заполнить какими то значениями - например если это возраст - то заполнить средним по датасету или нулем.

>> на будущее - в sklearn есть такой модуль - http://scikit-learn.org/stable/modules/impute.html но сейчас можете заполнить пропуски средствами pandas - метод fillna()

In [15]:
method='bfill'

##### Заполните пропущенные значения чем нибудь

In [16]:
simple_train = simple_train.fillna(simple_train.dropna()[columns].mean())
simple_test = simple_test.fillna(simple_train.dropna()[columns].mean())

# можно inplace делать такое, а можно переприсваивать.

In [17]:
simple_train

Sex        Age  Pclass  Survived
0      male  22.000000       3         0
1    female  38.000000       1         1
2    female  26.000000       3         1
3    female  35.000000       1         1
4      male  35.000000       3         0
5      male  28.184729       3         0
6      male  54.000000       1         0
7      male   2.000000       3         0
8    female  27.000000       3         1
9    female  14.000000       2         1
10   female   4.000000       3         1
11   female  58.000000       1         1
12     male  20.000000       3         0
13     male  39.000000       3         0
14   female  14.000000       3         0
15   female  55.000000       2         1
16     male   2.000000       3         0
17     male  28.184729       2         1
18   female  31.000000       3         0
19   female  28.184729       3         1
20     male  35.000000       2         0
21     male  34.000000       2         1
22   female  15.000000       3         1
23     male  28.000000       1         1
24   female   8.000000       3         0
25   female  38.000000       3         1
26     male  28.184729       3         0
27     male  19.000000       1         0
28   female  28.184729       3         1
29     male  28.184729       3         0
..      ...        ...     ...       ...
131    male  20.000000       3         0
132  female  47.000000       3         0
133  female  29.000000       2         1
134    male  25.000000       2         0
135    male  23.000000       2         0
136  female  19.000000       1         1
137    male  37.000000       1         0
138    male  16.000000       3         0
139    male  24.000000       1         0
140  female  28.184729       3         0
141  female  22.000000       3         1
142  female  24.000000       3         1
143    male  19.000000       3         0
144    male  18.000000       2         0
145    male  19.000000       2         0
146    male  27.000000       3         1
147  female   9.000000       3         0
148    male  36.500000       2         0
149    male  42.000000       2         0
150    male  51.000000       2         0
151  female  22.000000       1         1
152    male  55.500000       3         0
153    male  40.500000       3         0
154    male  28.184729       3         0
155    male  51.000000       1         0
156  female  16.000000       3         1
157    male  30.000000       3         0
158    male  28.184729       3         0
159    male  28.184729       3         0
160    male  44.000000       3         0

[161 rows x 4 columns]

In [18]:
simple_train.shape

(161, 4)

> мы чемпионы. Но мы понимаем, что алгоритм у нас метрический - он не понимает как померить близость векторов в которых содержатся строки

distance( [1,1,0,'мужик'], [1, 0, 1, 'принцесска'] )

> поэтому давайте заведем признак is_man который будет принимать значение 0 или 1.

##### Заведите бинарный признак отвечающий за пол. Строковый удалите

хинт - есть метод apply()

In [19]:
simple_train.Sex.replace(to_replace=dict(female=0, male=1), inplace=True)
simple_test.Sex.replace(to_replace=dict(female=0, male=1), inplace=True)

In [20]:
simple_train.head()


Sex   Age  Pclass  Survived
0    1  22.0       3         0
1    0  38.0       1         1
2    0  26.0       3         1
3    0  35.0       1         1
4    1  35.0       3         0

##### Сформируйте трейн и тест выборку, где в X лежат признаки 'Sex', 'Age', 'Pclass', а в у - Survived

Результат - numpy array

hint - у pandas есть метод drop() и атрибут values; Пощупайте их

In [21]:
X_train = simple_train[['Sex','Age','Pclass']].values
X_test = simple_test[['Sex','Age','Pclass']].values
y_train = simple_train['Survived'].values
y_test = simple_test['Survived'].values

In [22]:
max_ = X_train.max(axis=0)
min_ = X_train.min(axis=0)

X_train = (X_train - min_) / (max_ - min_)
X_test = (X_test - min_) / (max_ - min_)

In [23]:
X_train

array([[1.        , 0.30169588, 1.        ],
       [0.        , 0.52971355, 0.        ],
       [0.        , 0.3587003 , 1.        ],
       [0.        , 0.48696024, 0.        ],
       [1.        , 0.48696024, 1.        ],
       [1.        , 0.3898351 , 1.        ],
       [1.        , 0.75773122, 0.        ],
       [1.        , 0.01667379, 1.        ],
       [0.        , 0.3729514 , 1.        ],
       [0.        , 0.18768705, 0.5       ],
       [0.        , 0.045176  , 1.        ],
       [0.        , 0.81473564, 0.        ],
       [1.        , 0.27319367, 1.        ],
       [1.        , 0.54396466, 1.        ],
       [0.        , 0.18768705, 1.        ],
       [0.        , 0.77198233, 0.5       ],
       [1.        , 0.01667379, 1.        ],
       [1.        , 0.3898351 , 0.5       ],
       [0.        , 0.42995582, 1.        ],
       [0.        , 0.3898351 , 1.        ],
       [1.        , 0.48696024, 0.5       ],
       [1.        , 0.47270913, 0.5       ],
       [0.

In [24]:
assert isinstance(X_train, np.ndarray)
assert isinstance(X_test, np.ndarray)
assert isinstance(y_train, np.ndarray)
assert isinstance(y_test, np.ndarray)

In [25]:
assert X_train.shape[0] == y_train.shape[0]
assert X_test.shape[0] == y_test.shape[0]

In [26]:
assert not np.any(np.isnan(X_train)), 'у вас в данных есть пропущенные значения. Заполните их или удалите'
assert not np.any(np.isnan(X_test)), 'у вас в данных есть пропущенные значения. Заполните их или удалите'

##### Реализуйте KNN. Сами, как делали это на лекции. 

Можете улучшить его.
(например использовать kd-tree для быстрого поиска ближайших соседей, 
 или обходить соседей и класть расстояния в мин-кучу - тогда вы быстрее будете набирать их, без сортировки.)

In [27]:
X_train

array([[1.        , 0.30169588, 1.        ],
       [0.        , 0.52971355, 0.        ],
       [0.        , 0.3587003 , 1.        ],
       [0.        , 0.48696024, 0.        ],
       [1.        , 0.48696024, 1.        ],
       [1.        , 0.3898351 , 1.        ],
       [1.        , 0.75773122, 0.        ],
       [1.        , 0.01667379, 1.        ],
       [0.        , 0.3729514 , 1.        ],
       [0.        , 0.18768705, 0.5       ],
       [0.        , 0.045176  , 1.        ],
       [0.        , 0.81473564, 0.        ],
       [1.        , 0.27319367, 1.        ],
       [1.        , 0.54396466, 1.        ],
       [0.        , 0.18768705, 1.        ],
       [0.        , 0.77198233, 0.5       ],
       [1.        , 0.01667379, 1.        ],
       [1.        , 0.3898351 , 0.5       ],
       [0.        , 0.42995582, 1.        ],
       [0.        , 0.3898351 , 1.        ],
       [1.        , 0.48696024, 0.5       ],
       [1.        , 0.47270913, 0.5       ],
       [0.

In [28]:
len(X_train)

161

In [29]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0])

In [88]:
class KNN:
    """
    simple KNN classifier with O(n) complexity for memory,
    and O(n log n) complexity - for nn search.
    """
    
    def __init__(self, n):
        self.n = n
        
    def fit(self, X, y):
        self.X = X
        self.y = y
    
    def predict(self, X):
        y_hat = []
        assert len(X.shape) == 2
        for features in X:
            d=0
            for i,el in enumerate(features):
                d += (self.X[:,i]-el)**2
            d=np.sqrt(d)
            idx=np.argsort(d)[:self.n]
            counts=np.bincount(self.y[idx])
            prediction = np.argmax(counts)
            y_hat.append(prediction)
        return np.array(y_hat)

In [31]:
knn = KNN(5)

knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

##### посчитайте руками (не используя sklearn) качество вашего предсказания

In [32]:
acc = np.mean(y_pred == y_test)
print('доля правильных ответов:', acc)

доля правильных ответов: 0.7893296853625171


In [33]:
np.unique(y_pred)

array([0, 1])

> Мы получили бейслайн решение. Оно должно давать скорр в районе 0.76

____

In [34]:
### можете проверить себя

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7893296853625171


In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

np.unique(y_pred)

print(accuracy_score(y_test, y_pred))

0.7893296853625171


In [76]:
columns = ['Sex', 'Age', 'Pclass', 'Survived', 'Cabin', 'Fare', 'Embarked']
yo=df_titanic[columns].loc[:]

yo.Sex=yo.Sex.apply(lambda x:0 if x.strip() == 'female' else 1)
yo.Cabin = df_titanic.Cabin.apply(lambda x: x[0] if type(x) == str else np.nan)
yo=pd.get_dummies(data=yo, columns=['Embarked', 'Cabin'])
yo.head()

Sex   Age  Pclass  Survived     Fare  Embarked_C  Embarked_Q  Embarked_S  \
0    1  22.0       3         0   7.2500           0           0           1   
1    0  38.0       1         1  71.2833           1           0           0   
2    0  26.0       3         1   7.9250           0           0           1   
3    0  35.0       1         1  53.1000           0           0           1   
4    1  35.0       3         0   8.0500           0           0           1   

   Cabin_A  Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_T  
0        0        0        0        0        0        0        0        0  
1        0        0        1        0        0        0        0        0  
2        0        0        0        0        0        0        0        0  
3        0        0        1        0        0        0        0        0  
4        0        0        0        0        0        0        0        0

In [94]:
X=yo.drop('Survived',axis=1)
y=yo['Survived'].values

In [113]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1)
X_train,X_v, y_train, y_v = train_test_split(X_train, y_train,test_size=0.2, random_state=1)

In [114]:
mean=X_train.mean()
std = X_train.std()
X_train=X_train.fillna(mean)
X_train=((X_train-mean)/std).values
X_test=X_test.fillna(mean)
X_test=((X_test-mean)/std).values
X_v=X_v.fillna(mean)
X_v=((X_v-mean)/std).values

In [127]:
accuracy = {}
for i in range(1,30):
    knn=KNN(i)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_v)
    acc = accuracy_score(y_v, y_pred)
    print(i, ' : ', acc)
    accuracy[i]=acc

1  :  0.7972027972027972
2  :  0.8321678321678322
3  :  0.8251748251748252
4  :  0.8531468531468531
5  :  0.8531468531468531
6  :  0.8601398601398601
7  :  0.8461538461538461
8  :  0.8391608391608392
9  :  0.8671328671328671
10  :  0.8251748251748252
11  :  0.8531468531468531
12  :  0.8391608391608392
13  :  0.8391608391608392
14  :  0.8391608391608392
15  :  0.8391608391608392
16  :  0.8391608391608392
17  :  0.8391608391608392
18  :  0.8321678321678322
19  :  0.8321678321678322
20  :  0.8461538461538461
21  :  0.8321678321678322
22  :  0.8251748251748252
23  :  0.8251748251748252
24  :  0.8461538461538461
25  :  0.8531468531468531
26  :  0.8461538461538461
27  :  0.8391608391608392
28  :  0.8391608391608392
29  :  0.8391608391608392


In [128]:
best=max(accuracy, key=accuracy.get)

In [129]:
best

9

In [130]:
knn=KNN(best)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
acc=accuracy_score(y_test, y_pred)
print("dlya ", best, ' :',acc)

dlya  9  : 0.7374301675977654


##### TODO продолжение домашки